version: '3.8'
services:
  backend:
    network_mode: "bridge"
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://ep-super-flower-a9ysxa63-pooler.gwc.azure.neon.tech:5432/neondb
      - DB_USER=neondb_owner
      - DB_PASSWORD=npg_qhGurVQnt51K

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
       - ./localhost.pem:/app/localhost.pem:ro
       - ./localhost-key.pem:/app/localhost-key.pem:ro
