spring.application.name=backend


spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.servlet.session.timeout=15m

# server.port=8443
# server.ssl.enabled=false
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=qwerty123
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=my-ssl-cert
# server.ssl.client-auth=none

logging.level.root=DEBUG